# Commons

common:
  namespace: avx

appviewx:
  mountpath: /appviewx/dependencies/
  logsCapacityStorage: 5Gi
  mongodbpassword: w4qmnrHm18/uudk+si9fHgRLdgU/sWFeRmZOPoXQ96M=
  mongokey: o3nx09h95703joyyr0jvqhl6e
