{{- $dot := . }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pv-claim
  namespace: {{ $dot.Values.common.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $dot.Values.appviewx.logsCapacityStorage }}

