{{- $dot := . }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pv-claim
  namespace: {{ $dot.Values.common.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $dot.Values.appviewx.logsCapacityStorage }}

---
{{- $dot := . }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv-volume
  namespace: {{ $dot.Values.common.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ $dot.Values.appviewx.logsCapacityStorage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ $dot.Values.appviewx.mountpath }}/logs"

