# Commons

common:
  namespace: 
    - avx
  config: avx-common-config

appviewx:
  create: true
  moduleconfig: avx-platform-core-config
  replicas: 1
  registryurl: ""
  installation_user: "appviewx"
  installation_user_id: "1000"
  appviewx_base_image: "gcr.io/gcp-gke-cluster-poc/avx-cloud-managedservice:2020.3.0"
  appviewx_path: "/home/appviewx/appviewx/"
  appname: 
    - avx-platform-core:5202:8021:ClusterIP:20.3.0.0
  mountpath: /appviewx/dependencies/
  cpuRequest: "500m"
  memoryRequest: "500Mi"
  multi: "true"

hpa:
  cputhreshold: 400
  memorythreshold: 300
  maxreplica: 5
  
probe:
   path: "/services/health/check"
   port: 8021
   initialDelaySeconds: 30
   timeoutSeconds: 2
   periodSeconds: 15

health:
    path: '/services/health/metrics'
    port: '8021'
    scrape: 'true'

image:
  registry: gcr.io
  repository: gcp-gke-cluster-poc/avx-cloud-managedservice
  tag: 2020.3.0    
    

