{{- $dot := . }}
{{- range $key, $value := $dot.Values.common.namespace }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: web-http-gateway-{{ $value }}
  namespace: {{ $value }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts: 
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-http-vs-{{ $value }}
  namespace: {{ $value }}
spec:
  externalTrafficPolicy: Local
  hosts:
  - "*"
  gateways:
  - web-http-gateway-{{ $value }}
  http:
  - match:
    - uri:
        prefix: /scep
    route:
    - destination:
        host: avx-platform-gateway.{{ $value }}.svc.cluster.local
        port:
          number: 5302          
{{- end }}


